# This file was generated by GoReleaser. DO NOT EDIT.
cask "brr" do
  name "brr"
  desc "brr — autonomous AI coding loops for Claude Code"
  homepage "https://github.com/hl/brr"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brr"

  on_macos do
    on_intel do
      url "https://github.com/hl/brr/releases/download/v#{version}/brr_darwin_amd64.tar.gz"
      sha256 "23f49d077b9919f39c3722e68aa74afeb01ea22c4fcae1884637cf37c4be126c"
    end
    on_arm do
      url "https://github.com/hl/brr/releases/download/v#{version}/brr_darwin_arm64.tar.gz"
      sha256 "7a84ec0212185f7e4f4d3f61aee1110d54c95ccd0bc13d311119ebf371efbae8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hl/brr/releases/download/v#{version}/brr_linux_amd64.tar.gz"
      sha256 "06df47eeaa5135af7b08d4da26a5afb841d2eb7ca5be74ff8d5aff06e37c9cca"
    end
    on_arm do
      url "https://github.com/hl/brr/releases/download/v#{version}/brr_linux_arm64.tar.gz"
      sha256 "e3fc0b96da32460ba849fc5d56d5bde9f4810b1811c9aa1720df227eda660ddd"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brr"]
  end

  # No zap stanza required
end
