# This file was generated by GoReleaser. DO NOT EDIT.
cask "brr" do
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/hl/brr/releases/download/v#{version}/brr_darwin_amd64.tar.gz"
      sha256 "a074c8e2687e81925bc14e1786c1ffd9cd7d4bcf869e89c9bffa5c83ac8700f7"
    end
    on_arm do
      url "https://github.com/hl/brr/releases/download/v#{version}/brr_darwin_arm64.tar.gz"
      sha256 "88b5abec8145afd4a3c3a440e158fecaf38aea5fa82e14cc25292ac954d4660a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hl/brr/releases/download/v#{version}/brr_linux_amd64.tar.gz"
      sha256 "5645996c89dcee19f167ccd201c2de724bba9f7c73d54ce02cf25647e30eb845"
    end
    on_arm do
      url "https://github.com/hl/brr/releases/download/v#{version}/brr_linux_arm64.tar.gz"
      sha256 "810f3f136e5b2f5ef20044afc9bdd3eb1aede682137da63c3f84a7342e99cf69"
    end
  end

  name "brr"
  desc "brr — autonomous AI coding loops for Claude Code"
  homepage "https://github.com/hl/brr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "brr"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/brr"]
  end

  # No zap stanza required

end
