# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brr < Formula
  desc "brr — autonomous AI coding loops for Claude Code"
  homepage "https://github.com/hl/brr"
  version "0.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hl/brr/releases/download/v0.3.4/brr_darwin_amd64.tar.gz"
      sha256 "0b620b8c981cf8a817b9edeb3afcc4ee48d998d36a9443dc5b4fd5d627f47a52"

      define_method(:install) do
        bin.install "brr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hl/brr/releases/download/v0.3.4/brr_darwin_arm64.tar.gz"
      sha256 "f5017a9f821898a76a9705bfd2b9d65a72a04e686597d8e376afc0d024f52f05"

      define_method(:install) do
        bin.install "brr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hl/brr/releases/download/v0.3.4/brr_linux_amd64.tar.gz"
      sha256 "0f65c231b83ba75e8c0e959461c9774b5da5eca5ff25cccfeb36ab001c98ab0e"
      define_method(:install) do
        bin.install "brr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hl/brr/releases/download/v0.3.4/brr_linux_arm64.tar.gz"
      sha256 "22a4059cabf305d64258266b402746c4364a062f397a04ee8a73ae5c33d72f1e"
      define_method(:install) do
        bin.install "brr"
      end
    end
  end
end
