# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brr < Formula
  desc "brr — autonomous AI coding loops for Claude Code"
  homepage "https://github.com/hl/brr"
  version "0.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hl/brr/releases/download/v0.3.3/brr_darwin_amd64.tar.gz"
      sha256 "1506ee434050db13e6e9c574e183a1fbaa5baa24db8a2bbd7caf38411fa131ea"

      define_method(:install) do
        bin.install "brr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hl/brr/releases/download/v0.3.3/brr_darwin_arm64.tar.gz"
      sha256 "aebdc8d8058e88994786b2f12458a02dbc34723dca52a4c6fbd1e0475e028666"

      define_method(:install) do
        bin.install "brr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hl/brr/releases/download/v0.3.3/brr_linux_amd64.tar.gz"
      sha256 "9b880f6ee62429c1892f74b7f14a0d0f41ffaa81dcb47bbdeba23c746ee0e1bd"
      define_method(:install) do
        bin.install "brr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hl/brr/releases/download/v0.3.3/brr_linux_arm64.tar.gz"
      sha256 "ee652712317be84b28d2175127222df56b6fd292fe297f8281d80e50d4699d7e"
      define_method(:install) do
        bin.install "brr"
      end
    end
  end
end
